# Generated by Django 5.1.6 on 2025-11-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название адреса"),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="долгота"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="широта"
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
                "unique_together": {("name", "lon", "lat")},
            },
        ),
    ]
