# Generated by Django 5.1.6 on 2025-11-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="lat",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="широта"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="lon",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="долгота"
            ),
        ),
    ]
