# Generated by Django 5.2.9 on 2025-12-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0002_alter_address_lat_alter_address_lon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=250, verbose_name="название адреса"),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="долгота"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="широта"
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
                "unique_together": {("address", "lon", "lat")},
            },
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
