# Generated by Django 5.2.9 on 2025-12-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_place_delete_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="lat",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="широта"
            ),
        ),
        migrations.AlterField(
            model_name="place",
            name="lon",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, null=True, verbose_name="долгота"
            ),
        ),
    ]
