# Generated by Django 5.2.9 on 2025-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0004_alter_place_lat_alter_place_lon"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("address",)},
        ),
    ]
