# Generated by Django 5.2.9 on 2025-12-17 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0005_alter_place_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="place",
            unique_together={("lon", "lat")},
        ),
    ]
