# Generated by Django 5.2.7 on 2025-10-25 16:43

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0037_auto_20210125_1833"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="имя")),
                ("surname", models.CharField(max_length=100, verbose_name="фамилия")),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=15, region="RU", verbose_name="контактный телефон"
                    ),
                ),
                ("address", models.CharField(max_length=250, verbose_name="адрес")),
            ],
            options={
                "verbose_name": "заказ",
                "verbose_name_plural": "заказы",
                "unique_together": {("name", "surname", "address")},
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="количество продукта")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="foodcartapp.order",
                        verbose_name="продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "пункт заказа",
                "verbose_name_plural": "пункты заказа",
                "unique_together": {("product", "quantity")},
            },
        ),
    ]
