# Generated by Django 5.2.7 on 2025-10-25 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="order",
            unique_together={("surname", "name", "address")},
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="foodcartapp.order",
                verbose_name="заказ",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="foodcartapp.product",
                verbose_name="продукт",
            ),
        ),
    ]
