# Generated by Django 5.2.7 on 2025-11-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_alter_order_unique_together_orderitem_order_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="surname",
            new_name="lastname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="phone_number",
            new_name="phonenumber",
        ),
        migrations.AlterUniqueTogether(
            name="order",
            unique_together=set(),
        ),
    ]
