# Generated by Django 5.1.6 on 2025-11-04 15:10

import foodcartapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0040_rename_name_order_firstname_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.IntegerField(
                validators=[foodcartapp.models.validate_quantity],
                verbose_name="количество продукта",
            ),
        ),
    ]
