# Generated by Django 5.1.6 on 2025-11-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0041_alter_orderitem_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, null=True, verbose_name="цена"
            ),
        ),
    ]
