# Generated by Django 5.1.6 on 2025-11-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    def fill_prize_field(apps, schema_editor):
        OrderItem = apps.get_model('foodcartapp', 'OrderItem')
        for item in OrderItem.objects.select_related('product').all():
            if not item.price:
                item.price = item.product.price
                item.save()

    dependencies = [
        ("foodcartapp", "0042_orderitem_price"),
    ]

    operations = [
        migrations.RunPython(fill_prize_field),
    ]
