# Generated by Django 5.1.6 on 2025-11-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_auto_20251108_1850"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "необработанный"),
                    ("adopted", "принят"),
                    ("delivered", "доставляется"),
                    ("processed", "обработанный"),
                ],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="статус заказа",
            ),
        ),
    ]
