# Generated by Django 5.1.6 on 2025-11-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("pending", "необработанный"), ("processed", "обработанный")],
                db_index=True,
                default="pending",
                max_length=10,
                verbose_name="статус заказа",
            ),
        ),
    ]
