# Generated by Django 5.1.6 on 2025-11-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0045_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="комментарий к заказу"),
        ),
    ]
