# Generated by Django 5.1.6 on 2025-11-08 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0046_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата звонка"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="дата доставки"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="registration_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="дата регистарции",
            ),
        ),
    ]
