# Generated by Django 5.1.6 on 2025-11-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0047_order_called_date_order_delivered_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("electronic", "электронно"), ("cash", "наличными")],
                db_index=True,
                default="electronic",
                max_length=10,
                verbose_name="вид оплаты",
            ),
        ),
    ]
