# Generated by Django 5.1.6 on 2025-11-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0051_alter_order_restaurant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="restaurant",
        ),
    ]
