# Generated by Django 5.1.6 on 2025-11-22 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0053_order_restaurant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=250, verbose_name="название адреса"),
                ),
                (
                    "lon",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="долгота"
                    ),
                ),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=2, max_digits=3, verbose_name="широта"
                    ),
                ),
            ],
            options={
                "verbose_name": "адрес",
                "verbose_name_plural": "адреса",
                "unique_together": {("name", "lon", "lat")},
            },
        ),
        migrations.AddField(
            model_name="order",
            name="address_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                to="foodcartapp.address",
                verbose_name="id адреса",
            ),
        ),
    ]
