# Generated by Django 5.1.6 on 2025-11-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0054_address_order_address_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address_id",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
