# Generated by Django 5.2.9 on 2025-12-06 15:44

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0055_remove_order_address_id_delete_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="called_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="дата звонка"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivered_date",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="дата доставки"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("electronic", "электронно"), ("cash", "наличными")],
                db_index=True,
                max_length=10,
                verbose_name="вид оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="phonenumber",
            field=phonenumber_field.modelfields.PhoneNumberField(
                db_index=True,
                max_length=15,
                region="RU",
                verbose_name="контактный телефон",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="foodcartapp.order",
                verbose_name="заказ",
            ),
        ),
    ]
