# Generated by Django 5.2.9 on 2025-12-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "foodcartapp",
            "0056_alter_order_called_date_alter_order_delivered_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=8, verbose_name="цена"
            ),
        ),
    ]
