# Generated by Django 5.2.9 on 2025-12-17 15:08

import foodcartapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0058_alter_orderitem_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[foodcartapp.models.validate_quantity],
                verbose_name="цена",
            ),
        ),
    ]
